# ================ Gets all cards
###
GET http://localhost:3001/cards

# ================ Gets cards from specific deck
GET http://localhost:3001/decks/1/cards

###

# ================ Get first card from deck
GET http://localhost:3001/decks/1/cards?_limit=1



###

# ================ Create Card
POST http://localhost:3001/cards HTTP/1.1
content-type: application/json

{
  "id": 5,
  "front": "Pythagorean Identity",
  "back": "* some identity image",
  "deckId": 3
}


###
# ================ Update Card
PATCH http://localhost:3001/cards/11 HTTP/1.1
content-type: application/json

{
  "front": "front edited",
  "back": "back edited",
  "deckId": 4
}

###
# ================ Delete Card

DELETE http://localhost:3001/cards/16 HTTP/1.1


